// ============================================================
//  v0id Bio-Link — DEMO DATA (offline preview mode)
//  Used automatically when Supabase keys are not configured,
//  so you can see the full site immediately. Mirror of the
//  schema.sql seed — edit freely, it only affects preview.
// ============================================================

window.DEMO_DATA = {
  settings: {
    id: 1,
    font_primary: 'Space Grotesk',
    font_secondary: 'Inter',
    glow_intensity: 0.65,
    color_accent: '#7c3aed',
    color_bg: '#050308',
    bg_type: 'image',
    bg_url: 'assets/demo/bg-demo.png',
    bg_blur: 2,
    bg_dim: 0.55,
    bg_glow: 0.5,
    music_url: '',
    music_autoplay: false,
    music_volume: 0.5,
    music_start: 0,
    music_end: 0,
    music_title: '',
    music_cover: '',
    music_pstyle: 'bg',
    music_pcolor: '',
    music_pblur: 10,
    music_pbg: '',
    discord_user_id: '',
  },
  playlist: [],
  profile: {
    id: 1,
    avatar_url: 'assets/avatar.svg',
    owner_badge: 'Owner',
    display_name_ar: 'v0id',
    display_name_en: 'v0id',
    location_ar: 'الجزائر',
    location_en: 'Algeria',
    age: '',
    occupation_ar: 'مطوّر برمجيات',
    occupation_en: 'Software Developer',
    bio_ar: 'أنشئ برامج ومواقع من الصفر — من واجهات متوهجة مبتكرة إلى برامج تحسين أداء الألعاب وأنظمة حسابات آمنة. كل مشروع عندي يبدأ من فكرة حقيقية وينتهي بمنتج جاهز للاستخدام.',
    bio_en: 'I build software and websites from scratch — from creative glowing UIs to game performance boosters and secure account systems. Every project starts from a real idea and ends as a ready-to-use product.',
    goals_ar: 'بناء منتجات أكبر تجمع الأداء والجودة، والوصول لعدد أكبر من اللاعبين والمستخدمين.',
    goals_en: 'Building bigger products that combine performance and quality, reaching more gamers and users.',
    journey_ar: 'بدأت من فضول نحو كيف تعمل الألعاب والبرامج. جربت وبنيت وتعلّمت من الأخطاء حتى صار جلّ وقتي في تحويل الأفكار إلى واقع ملموس — كل خطوة علّمتني شيئاً جديداً.',
    journey_en: 'It started with curiosity about how games and software work. I experimented, built, and learned from mistakes, until my time became about turning ideas into reality — every step taught me something new.',
    skills_ar: 'C++, ImGui, JavaScript, Next.js, PHP, MySQL, SQL, CSS، تصميم واجهات, وأساسيات الأمان.',
    skills_en: 'C++, ImGui, JavaScript, Next.js, PHP, MySQL, SQL, CSS, UI design, and security fundamentals.',
  },
  socials: [
    { id: 's1', platform: 'discord',  label: 'Discord',   url: 'https://discord.com/users/0',      color: '#5865F2', icon: '', sort_order: 1, visible: true },
    { id: 's2', platform: 'github',   label: 'GitHub',    url: 'https://github.com/laminieyt54-afk', color: '#f0f6fc', icon: '', sort_order: 2, visible: true },
    { id: 's3', platform: 'instagram',label: 'Instagram', url: 'https://instagram.com/',           color: '#E1306C', icon: '', sort_order: 3, visible: true },
    { id: 's4', platform: 'youtube',  label: 'YouTube',   url: 'https://youtube.com/',             color: '#FF0000', icon: '', sort_order: 4, visible: true },
    { id: 's5', platform: 'tiktok',   label: 'TikTok',    url: 'https://tiktok.com/',              color: '#00f2ea', icon: '', sort_order: 5, visible: true },
  ],
  projects: [
    {
      id: 'p1',
      title_ar: 'OptiFrame', title_en: 'OptiFrame',
      desc_ar: 'برنامج ويندوز لتحسين أداء الألعاب (FPS booster): واجهة عصرية بأسلوب AI، قائمة "AI Boost" تحسّن ألعابك، إصلاحات مشاكل الأداء، إزالة البرامج المزعجة (Bloatware)، أدوات ألعاب، حفظ نسخ احتياطية، وتقنية ذكاء اصطناعي تضبط إعداداتك الأمثل — كل ذلك في برنامج واحد سهل التثبيت.',
      desc_en: 'A Windows game performance booster: a modern AI-styled UI with an "AI Boost" menu that optimizes your games, performance fixes, bloatware removal, gaming tools, registry backups, and AI that applies the optimal settings for your PC — all in one easy-to-install program.',
      tags: 'C++, ImGui, Windows, KeyAuth',
      color: '#7c3aed', media_type: 'image',
      image_url: 'assets/projects/optiframe-preview.svg', video_url: '',
      github_url: 'https://github.com/laminieyt54-afk/OptiFrame',
      download_url: 'https://github.com/laminieyt54-afk/OptiFrame/releases/download/v1.0.0/OptiFrame_Setup_1.0.0.exe',
      external_url: '', sort_order: 1, visible: true,
    },
    {
      id: 'p2',
      title_ar: 'خطواتي', title_en: 'Khutowati',
      desc_ar: 'منصة مغاربية لرحلة البكالوريا وتطوير الذات والأهداف — مصممة للطلاب في الجزائر والمغرب وتونس: حساب مخصص بدولتك وجنسك وحالتك اليومية، تتبع أهدافك الدراسية والشخصية، وبيئة داكنة أنيقة بتصميم نيون أخضر تجعل تعبك اليومي خطوة حقيقية نحو هدفك.',
      desc_en: 'A Maghreb platform for the Baccalaureate journey, self-development and goals — built for students in Algeria, Morocco and Tunisia: an account tailored to your country, gender and daily status, tracking your study and personal goals, wrapped in a sleek dark UI with neon-green design.',
      tags: 'Next.js, React, Tailwind, Supabase, RTL',
      color: '#22c55e', media_type: 'image',
      image_url: 'assets/projects/khutowati-preview.svg', video_url: '',
      github_url: 'https://github.com/laminieyt54-afk',
      download_url: '', external_url: 'https://khutowati.vercel.app/signin',
      sort_order: 2, visible: true,
    },
  ],
  about: [
    {
      id: 'a1',
      title_ar: 'رحلتي في البرمجة', title_en: 'My Coding Journey',
      body_ar: 'بدأت من فضول نحو كيف تعمل الألعاب والبرامج، وتعلّمت أن بناء الشيء بنفسك هو أفضل طريقة لفهمه. جربت لغات وأدوات كثيرة حتى وجدت الأسلوب الذي يجمع الأداء مع الجمال — وكل مشروع أطلقه اليوم هو ثمرة تلك الرحلة.',
      body_en: 'It started with curiosity about how games and software work, and I learned that building things yourself is the best way to understand them. I tried many languages and tools until I found a style that blends performance with beauty.',
      icon: 'journey', sort_order: 1, visible: true,
    },
    {
      id: 'a2',
      title_ar: 'مهاراتي', title_en: 'My Skills',
      body_ar: 'أطوّر برامج سطح المكتب (C++ و ImGui) ونظم الواجهات المتوهجة، وأبني مواقع كاملة (JavaScript و Next.js) مع قواعد بيانات وأمن حسابات (PHP و MySQL و SQL و KeyAuth و Supabase). أحب التصميم بقدر ما أحب البناء.',
      body_en: 'I build desktop apps (C++ & ImGui) and glowing UI frameworks, and complete websites (JavaScript & Next.js) with databases and account security (PHP, MySQL, SQL, KeyAuth, Supabase). I love design as much as I love engineering.',
      icon: 'skills', sort_order: 2, visible: true,
    },
    {
      id: 'a3',
      title_ar: 'أهدافي وفلسفتي', title_en: 'Goals & Philosophy',
      body_ar: 'أؤمن أن الأداة الجيدة تصنع فرقاً حقيقياً في حياة مستخدمها — سواء لاعب يحتاج رفع الأداء أو طالب يبني مساره الدراسي. أطمح لمنتجات أكبر تجمع الأداء والجودة، وأسعى دائماً أن تكون تجربة المستخدم ممتعةً ونظيفة.',
      body_en: 'I believe a good tool makes a real difference in its user\u2019s life — a gamer who needs a performance boost or a student building their academic path. I aim for bigger products that combine performance and quality.',
      icon: 'future', sort_order: 3, visible: true,
    },
  ],
};